### ISSUE TITLE
If I add an environment using the preview package, it works using preview.el but not with this package.

### ISSUE THREAD

**Issue by vslavkin** [ultronozm/czm-preview.el#1]
If I add these two lines to my .tex file:
\usepackage[displaymath, textmath, graphics]{preview}
\PreviewEnvironment{tikzpicture}

I can use preview.el to preview the tikzpicture. But using czm-preview, the tikzpicture doesnt work

Also if you put 
(eval-after-load "preview"
  '(add-to-list 'preview-default-preamble
  "\\PreviewEnvironment{tikzpicture}" t))

**Comment by ultronozm** [comment]
What is meant here by “tex file”? The file being edited, or
“preview-master.tex”?

Have you added \usepackage{tikzpicture} to preview-master?

**Comment by vslavkin** [comment]
It's the file being edited, not preview-master.tex
I'll try to add the \usepackage{tikz} to the preview-master and switch to it

**Comment by vslavkin** [comment]
I could get it to work. I tried with and without the preview-master, sometimes it doesn't do anything and sometimes is tries to render something and only displays an empty square (and latex throws an error). It only previews tikzpicture s if they are inside a math/equation/preview environment.
I tried to add tikzpicture to czm-preview-valid-environments, but that didn't work
Meanwhile preview-latex does work.

**Comment by ultronozm** [comment]
So just to be clear:

1. Is it still the case that everything works fine if the tikzpictures are
inside a math environment?

2. The disparity you're observing is that you've succeeded in getting
built-in preview-latex to render tikzpictures without being in a math
environment, but haven't been able to do so for this package?

**Comment by ultronozm** [comment]
Assuming the answer is "yes", I just pushed an update that should hopefully
make tikzpictures work seamlessly, even when the tikzpicture is not in a
math environment.  I've updated both the code and the provided
preview-master.tex.  Please try it out and let me know if there are any
issues.
